### ISSUE TITLE
Trigger GitHub Actions on PR

### ISSUE THREAD

**Issue by huyfififi** [mie-h/sprout#41]
**Is your feature request related to a problem? Please describe.**
GitHub Actions are not triggered when creating pull requests from forked repositories

**Describe the solution you'd like**
We might want to update the conditions to trigger the workflows, such as 

```
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    ...
```
